name: Pipeline Despliegue Etsy
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: 1. Pruebas Automáticas
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar Tests Unitarios
        run: npm test

  deploy:
    name: 2. Despliegue Automático
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
      - name: Generar catalogo de funciones
        run: node scripts/generar-manifest.js
      - name: Preparar página web
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4