name: Pipeline Despliegue Etsy
   on:
     push:
       branches: [ main ]
   jobs:
     test:
       name: 1. Pruebas Automáticas
       runs-on: ubuntu-latest
       steps:
         - name: Descargar el código
           uses: actions/checkout@v4
         - name: Ejecutar Tests Unitarios
           run: npm test
     deploy:
       name: 2. Despliegue Automático
       needs: test
       runs-on: ubuntu-latest
       steps:
         - name: Descargar el código
           uses: actions/checkout@v4
         - name: Subir a Producción
           run: npm run deploy